"""create routes table

Revision ID: 503ead3a6c2d
Revises: 
Create Date: 2026-02-22 21:02:15.753615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503ead3a6c2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('train_number', sa.String(), nullable=False),
    sa.Column('departure_station', sa.String(), nullable=False),
    sa.Column('arrival_station', sa.String(), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_arrival_station'), 'routes', ['arrival_station'], unique=False)
    op.create_index(op.f('ix_routes_departure_station'), 'routes', ['departure_station'], unique=False)
    op.create_index(op.f('ix_routes_source'), 'routes', ['source'], unique=False)
    op.create_index(op.f('ix_routes_train_number'), 'routes', ['train_number'], unique=False)
    op.create_index(op.f('ix_routes_travel_date'), 'routes', ['travel_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_travel_date'), table_name='routes')
    op.drop_index(op.f('ix_routes_train_number'), table_name='routes')
    op.drop_index(op.f('ix_routes_source'), table_name='routes')
    op.drop_index(op.f('ix_routes_departure_station'), table_name='routes')
    op.drop_index(op.f('ix_routes_arrival_station'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
