"""split routes and prices

Revision ID: 53d2a2855de0
Revises: 503ead3a6c2d
Create Date: 2026-03-06 22:04:10.754088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53d2a2855de0'
down_revision: Union[str, Sequence[str], None] = '503ead3a6c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routes', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               postgresql_using='id::varchar')
    op.drop_column('routes', 'price')
    op.drop_column('routes', 'currency')
    op.drop_column('routes', 'scraped_at')
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_route_id'), 'prices', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('scraped_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('routes', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('routes', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('routes', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_prices_route_id'), table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
