"""Add is_couchette to Price

Revision ID: b7ff82388d46
Revises: 53d2a2855de0
Create Date: 2026-03-06 22:30:55.954422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ff82388d46'
down_revision: Union[str, Sequence[str], None] = '53d2a2855de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('is_couchette', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'is_couchette')
    # ### end Alembic commands ###
